-- 202610060005_split_share_invite_redemption.sql
-- One-time, authenticated invite redemption plus command-time split expiry checks.
-- The invite preimage is generated by the PAL with a CSPRNG and is never stored here;
-- only its SHA-256 digest is passed to this server-only function.
BEGIN;

ALTER TABLE public.split_shares
  ADD COLUMN invite_consumed_at timestamptz,
  ADD CONSTRAINT split_shares_invite_consumption_check CHECK (
    invite_consumed_at IS NULL OR
    (invite_token_sha256 IS NOT NULL AND participant_user_id IS NOT NULL)
  );

COMMENT ON COLUMN public.split_shares.invite_consumed_at IS
  'Server-side one-time invite-claim marker; set atomically with participant_user_id. It is not payment authorization.';

CREATE OR REPLACE FUNCTION app_private.validate_split_share_invite_expiry()
RETURNS trigger LANGUAGE plpgsql
SET search_path = pg_catalog, public, app_private
AS $$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.invite_consumed_at IS NOT NULL THEN
    RAISE EXCEPTION 'invite consumption must use the atomic claim function' USING ERRCODE = '55000';
  END IF;
  IF NEW.invite_token_sha256 IS NOT NULL AND
     (NEW.expires_at IS NULL OR NEW.expires_at <= NEW.created_at) THEN
    RAISE EXCEPTION 'an invite token requires a future share expiry' USING ERRCODE = '22023';
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD.invite_consumed_at IS NOT NULL AND
       (NEW.invite_consumed_at IS DISTINCT FROM OLD.invite_consumed_at OR
        NEW.invite_token_sha256 IS DISTINCT FROM OLD.invite_token_sha256 OR
        NEW.expires_at IS DISTINCT FROM OLD.expires_at) THEN
      RAISE EXCEPTION 'a consumed invite cannot be changed or reissued' USING ERRCODE = '55000';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER split_shares_invite_expiry_guard
  BEFORE INSERT OR UPDATE OF invite_token_sha256, expires_at, created_at, invite_consumed_at
  ON public.split_shares FOR EACH ROW
  EXECUTE FUNCTION app_private.validate_split_share_invite_expiry();

-- Called only by the PAL after it authenticates the actor and hashes the raw invite token.
-- Locking both rows serializes concurrent redemptions and bill closure. Repeating the same
-- claim for the already-bound actor is a no-op response; another actor cannot reuse it.
CREATE OR REPLACE FUNCTION app_private.claim_split_share_invite(
  p_actor_user_id uuid,
  p_split_share_id uuid,
  p_invite_token_sha256 bytea
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, app_private
AS $$
DECLARE
  v_share record;
  v_now timestamptz;
BEGIN
  IF p_actor_user_id IS NULL OR p_split_share_id IS NULL OR
     p_invite_token_sha256 IS NULL OR octet_length(p_invite_token_sha256) <> 32 THEN
    RAISE EXCEPTION 'invalid invite claim envelope' USING ERRCODE = '22023';
  END IF;

  SELECT s.*, b.split_state AS bill_state, b.closes_at AS bill_closes_at
    INTO v_share
    FROM public.split_shares s
    JOIN public.split_bills b ON b.split_bill_id = s.split_bill_id
    WHERE s.split_share_id = p_split_share_id
    FOR UPDATE OF s, b;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'invite unavailable' USING ERRCODE = '42501';
  END IF;
  IF v_share.invite_token_sha256 IS DISTINCT FROM p_invite_token_sha256 THEN
    RAISE EXCEPTION 'invite unavailable' USING ERRCODE = '42501';
  END IF;

  IF v_share.invite_consumed_at IS NOT NULL THEN
    IF v_share.participant_user_id = p_actor_user_id THEN
      RETURN jsonb_build_object('split_share_id', p_split_share_id, 'result', 'already_claimed');
    END IF;
    RAISE EXCEPTION 'invite unavailable' USING ERRCODE = '42501';
  END IF;

  -- Evaluate wall-clock time after acquiring the locks so concurrent waits cannot extend validity.
  v_now := clock_timestamp();
  IF v_share.bill_state <> 'open' OR
     v_share.share_state IN ('paid', 'cancelled', 'expired') OR
     v_share.expires_at IS NULL OR v_share.expires_at <= v_now OR
     (v_share.bill_closes_at IS NOT NULL AND v_share.bill_closes_at <= v_now) OR
     (v_share.participant_user_id IS NOT NULL AND v_share.participant_user_id <> p_actor_user_id) THEN
    RAISE EXCEPTION 'invite unavailable' USING ERRCODE = '42501';
  END IF;

  UPDATE public.split_shares
    SET participant_user_id = COALESCE(participant_user_id, p_actor_user_id),
        invite_consumed_at = v_now
    WHERE split_share_id = p_split_share_id AND invite_consumed_at IS NULL;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'invite unavailable' USING ERRCODE = '42501';
  END IF;
  RETURN jsonb_build_object('split_share_id', p_split_share_id, 'result', 'claimed');
END;
$$;
REVOKE ALL ON FUNCTION app_private.claim_split_share_invite(uuid, uuid, bytea)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION app_private.claim_split_share_invite(uuid, uuid, bytea) TO service_role;

-- Preserve the opened-share immutability rule while permitting exactly one transition that
-- consumes an unexpired invite and binds it to the authenticated claimant.
CREATE OR REPLACE FUNCTION app_private.guard_open_split_share()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, app_private AS $$
DECLARE
  v_state public.split_bill_state;
  v_bill_id uuid;
  v_closes_at timestamptz;
  v_now timestamptz;
  v_claim_transition boolean := false;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_bill_id := OLD.split_bill_id;
  ELSE
    v_bill_id := NEW.split_bill_id;
  END IF;
  SELECT split_state, closes_at INTO v_state, v_closes_at
    FROM public.split_bills WHERE split_bill_id = v_bill_id;

  IF TG_OP = 'DELETE' THEN
    IF v_state IS DISTINCT FROM 'draft' THEN
      RAISE EXCEPTION 'share membership and amount cannot change after bill opens' USING ERRCODE = '55000';
    END IF;
    RETURN OLD;
  END IF;
  IF TG_OP = 'INSERT' THEN
    IF v_state IS DISTINCT FROM 'draft' THEN
      RAISE EXCEPTION 'shares can be added only while a bill is a draft' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
  END IF;

  IF OLD.invite_consumed_at IS NOT NULL AND
     (NEW.invite_consumed_at IS DISTINCT FROM OLD.invite_consumed_at OR
      NEW.invite_token_sha256 IS DISTINCT FROM OLD.invite_token_sha256 OR
      NEW.expires_at IS DISTINCT FROM OLD.expires_at) THEN
    RAISE EXCEPTION 'a consumed invite cannot be changed or reissued' USING ERRCODE = '55000';
  END IF;

  IF OLD.invite_consumed_at IS NULL AND NEW.invite_consumed_at IS NOT NULL THEN
    v_now := clock_timestamp();
    v_claim_transition := v_state = 'open' AND
      OLD.invite_token_sha256 IS NOT NULL AND
      NEW.invite_token_sha256 IS NOT DISTINCT FROM OLD.invite_token_sha256 AND
      NEW.split_bill_id IS NOT DISTINCT FROM OLD.split_bill_id AND
      NEW.amount_minor IS NOT DISTINCT FROM OLD.amount_minor AND
      NEW.expires_at IS NOT DISTINCT FROM OLD.expires_at AND
      NEW.share_state IS NOT DISTINCT FROM OLD.share_state AND
      NEW.latest_payment_intent_id IS NOT DISTINCT FROM OLD.latest_payment_intent_id AND
      NEW.created_at IS NOT DISTINCT FROM OLD.created_at AND
      NEW.participant_user_id IS NOT NULL AND
      (OLD.participant_user_id IS NULL OR NEW.participant_user_id = OLD.participant_user_id) AND
      OLD.share_state NOT IN ('paid', 'cancelled', 'expired') AND
      NEW.expires_at IS NOT NULL AND NEW.expires_at > v_now AND
      (v_closes_at IS NULL OR v_closes_at > v_now);
    IF NOT v_claim_transition THEN
      RAISE EXCEPTION 'invalid split-share invite consumption' USING ERRCODE = '55000';
    END IF;
  END IF;

  IF v_state IS DISTINCT FROM 'draft' AND
     (NEW.split_bill_id IS DISTINCT FROM OLD.split_bill_id OR
      NEW.amount_minor IS DISTINCT FROM OLD.amount_minor OR
      NEW.expires_at IS DISTINCT FROM OLD.expires_at OR
      (NEW.participant_user_id IS DISTINCT FROM OLD.participant_user_id AND NOT v_claim_transition) OR
      (NEW.invite_token_sha256 IS DISTINCT FROM OLD.invite_token_sha256 AND NOT v_claim_transition)) THEN
    RAISE EXCEPTION 'share membership and amount cannot change after bill opens' USING ERRCODE = '55000';
  END IF;

  IF NEW.invite_consumed_at IS DISTINCT FROM OLD.invite_consumed_at AND NOT v_claim_transition THEN
    RAISE EXCEPTION 'invalid split-share invite consumption' USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END;
$$;

-- Extend the existing invariant to all payment-intent amount/currency changes and to the
-- quote-authorization command. Passage of time is checked on commands, not by a clock trigger.
CREATE OR REPLACE FUNCTION app_private.assert_split_payment_owner()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, app_private
AS $$
DECLARE
  v_participant uuid;
  v_state public.split_bill_state;
  v_share_state public.split_share_state;
  v_currency char(3);
  v_amount bigint;
  v_share_expires_at timestamptz;
  v_bill_closes_at timestamptz;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF NEW.split_share_id IS DISTINCT FROM OLD.split_share_id OR
       NEW.payment_origin IS DISTINCT FROM OLD.payment_origin THEN
      RAISE EXCEPTION 'payment origin and split-share binding are immutable' USING ERRCODE = '55000';
    END IF;
  END IF;
  IF NEW.split_share_id IS NULL THEN RETURN NEW; END IF;

  SELECT s.participant_user_id, b.split_state, s.share_state, b.currency, s.amount_minor,
         s.expires_at, b.closes_at
    INTO v_participant, v_state, v_share_state, v_currency, v_amount,
         v_share_expires_at, v_bill_closes_at
    FROM public.split_shares s
    JOIN public.split_bills b ON b.split_bill_id = s.split_bill_id
    WHERE s.split_share_id = NEW.split_share_id;
  IF NOT FOUND OR v_participant IS NULL OR v_participant <> NEW.user_id OR
     NEW.currency <> v_currency OR NEW.requested_amount_minor <> v_amount THEN
    RAISE EXCEPTION 'payment intent does not match its split share' USING ERRCODE = '42501';
  END IF;

  IF NEW.payment_state IN ('created', 'lookup_pending', 'quoting', 'quoted', 'user_authorized') AND
     (v_state <> 'open' OR v_share_state IN ('paid', 'cancelled', 'expired') OR
      (v_share_expires_at IS NOT NULL AND v_share_expires_at <= clock_timestamp()) OR
      (v_bill_closes_at IS NOT NULL AND v_bill_closes_at <= clock_timestamp())) THEN
    RAISE EXCEPTION 'split share is closed, expired, or no longer eligible' USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER payment_intents_split_owner_check ON public.payment_intents;
CREATE TRIGGER payment_intents_split_owner_check
  BEFORE INSERT OR UPDATE OF split_share_id, user_id, payment_origin, currency,
      requested_amount_minor, payment_state
  ON public.payment_intents FOR EACH ROW
  EXECUTE FUNCTION app_private.assert_split_payment_owner();

COMMIT;
